$(".proj-slider").owlCarousel({
    loop:false,
    margin:24,
    nav:true,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:2
        }
    }
});